-- ================================================================= --
--  既存テーブルの削除（起動時に毎回クリーンな状態にするため）
-- ================================================================= --
DROP TABLE vet_specialties IF EXISTS;
DROP TABLE vets IF EXISTS;
DROP TABLE specialties IF EXISTS;
DROP TABLE visits IF EXISTS;
DROP TABLE prescriptions IF EXISTS;
DROP TABLE billings IF EXISTS;
DROP TABLE hotel_stays IF EXISTS;
DROP TABLE trimming_appointments IF EXISTS;
DROP TABLE hospital_reservations IF EXISTS;
DROP TABLE pets IF EXISTS;
DROP TABLE types IF EXISTS;
DROP TABLE owners IF EXISTS;


-- ================================================================= --
--  既存テーブルの作成
-- ================================================================= --
CREATE TABLE vets (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(30),
  last_name  VARCHAR(30)
);
CREATE INDEX vets_last_name ON vets (last_name);

CREATE TABLE specialties (
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(80)
);
CREATE INDEX specialties_name ON specialties (name);

CREATE TABLE vet_specialties (
  vet_id       INTEGER NOT NULL,
  specialty_id INTEGER NOT NULL
);
ALTER TABLE vet_specialties ADD CONSTRAINT fk_vet_specialties_vets FOREIGN KEY (vet_id) REFERENCES vets (id);
ALTER TABLE vet_specialties ADD CONSTRAINT fk_vet_specialties_specialties FOREIGN KEY (specialty_id) REFERENCES specialties (id);

CREATE TABLE types (
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(80)
);
CREATE INDEX types_name ON types (name);

CREATE TABLE owners (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(30),
  last_name  VARCHAR(30),
  address    VARCHAR(255),
  city       VARCHAR(80),
  telephone  VARCHAR(20)
);
CREATE INDEX owners_last_name ON owners (last_name);

CREATE TABLE pets (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(30),
  birth_date DATE,
  type_id    INTEGER NOT NULL,
  owner_id   INTEGER NOT NULL
);
ALTER TABLE pets ADD CONSTRAINT fk_pets_owners FOREIGN KEY (owner_id) REFERENCES owners (id);
ALTER TABLE pets ADD CONSTRAINT fk_pets_types FOREIGN KEY (type_id) REFERENCES types (id);
CREATE INDEX pets_name ON pets (name);

CREATE TABLE visits (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id      INTEGER NOT NULL,
  visit_date  DATE,
  description VARCHAR(255)
);
ALTER TABLE visits ADD CONSTRAINT fk_visits_pets FOREIGN KEY (pet_id) REFERENCES pets (id);
CREATE INDEX visits_pet_id ON visits (pet_id);


-- ================================================================= --
--  新規追加したテーブルの作成
-- ================================================================= --

CREATE TABLE hospital_reservations (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id              INTEGER NOT NULL,
    vet_id              INTEGER NOT NULL,
    reservation_time    TIMESTAMP,
    description         VARCHAR(255)
);
ALTER TABLE hospital_reservations ADD CONSTRAINT fk_hospital_reservations_pets FOREIGN KEY (pet_id) REFERENCES pets (id);
ALTER TABLE hospital_reservations ADD CONSTRAINT fk_hospital_reservations_vets FOREIGN KEY (vet_id) REFERENCES vets (id);

CREATE TABLE trimming_appointments (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id              INTEGER NOT NULL,
    appointment_time    TIMESTAMP,
    course              VARCHAR(255),
    trimmer_name        VARCHAR(255)
);
ALTER TABLE trimming_appointments ADD CONSTRAINT fk_trimming_appointments_pets FOREIGN KEY (pet_id) REFERENCES pets (id);

CREATE TABLE hotel_stays (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id              INTEGER NOT NULL,
    check_in_date       DATE,
    check_out_date      DATE,
    room_number         VARCHAR(255)
);
ALTER TABLE hotel_stays ADD CONSTRAINT fk_hotel_stays_pets FOREIGN KEY (pet_id) REFERENCES pets (id);

CREATE TABLE billings (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stay_id             INTEGER NOT NULL,
    amount              DECIMAL(10, 2),
    payment_date        DATE
);
ALTER TABLE billings ADD CONSTRAINT fk_billings_hotel_stays FOREIGN KEY (stay_id) REFERENCES hotel_stays (id);

CREATE TABLE prescriptions (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id      INTEGER NOT NULL,
    medicine_name       VARCHAR(255),
    quantity            INTEGER
);
ALTER TABLE prescriptions ADD CONSTRAINT fk_prescriptions_hospital_reservations FOREIGN KEY (reservation_id) REFERENCES hospital_reservations (id);
